### ISSUE TITLE
Is the full dependency dataset available?

### ISSUE THREAD

**Issue by szhorvat** [jwodder/wheelodex#6]
I am looking to analyse the dependency graph between Python packages. Does Wheelodex make this data available as a single download?

**Comment by jwodder** [comment]
It does not, as I feel the size of the data would be a bit prohibitive.  For example, I just ran a query on a database backup from a couple days ago to fetch a list of all (project name, dependency name) pairs, and the resulting CSV file was 1,571,369 lines long and 36 MB.

I could provide you with this CSV if you want it (How would you like it sent?), but note the following caveats which may or may not make it unsuitable for your research:

- For each project, only the dependencies from one wheel of the most recent version are recorded.  If a project has multiple wheels, the choice of which one is used is effectively arbitrary.
- Only names of dependencies are recorded, not version requirements or extras.
- Extra requirements are included without distinction.
- If all of a project's wheels are greater than 5 MiB, no data for those wheels is present.  If a previous version of such a project had wheels below the cutoff size, data for the older version may still be present.

**Comment by szhorvat** [comment]
What you describe, (package, dependent) pairs, would be excellent. Does this list for the _whole database_ take only 36 MB?

The limitations you mention are not a serious issue, nor it is a problem if the database is a little bit outdated.

If the compressed version of the file is below 25 MB, an email (see my profile) would be great. Otherwise would you be able to host the file somewhere (Google Drive or similar)? I can let you know more about the project in email.

**Comment by jwodder** [comment]
> Does this list for the *whole database* take only 36 MB?

Yes, it does.  When gzipped, it's 9.1 MB.

I'll be sending you an e-mail from (my username) at gmail.com shortly.
